release: fix cargo publish
Specifies a version for the sawp-ffi dependency and adds a qa check for
cargo publish.

cargo publish was failing with the following error:

```
error: all dependencies must have a version specified when publishing.
dependency `sawp-ffi` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```